# Generated by Django 6.0.3 on 2026-03-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_quiz_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
    ]
