# Generated by Django 6.0.3 on 2026-03-17 21:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. CAT 2023 Slot 1', max_length=255)),
                ('exam_type', models.CharField(choices=[('CAT', 'Common Admission Test'), ('UPSC', 'Union Public Service Commission'), ('JEE', 'Joint Entrance Examination')], default='CAT', max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=120)),
                ('is_official', models.BooleanField(default=True, help_text="True if it's a past year paper")),
                ('is_pro', models.BooleanField(default=False, help_text="True if it's an AI-generated Certified Mock")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_text', models.TextField(help_text='The passage or data description')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('FINISHED', 'Finished')], default='STARTED', max_length=20)),
                ('total_score', models.FloatField(default=0.0)),
                ('predicted_percentile', models.FloatField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('TITA', 'Type In The Answer')], default='MCQ', max_length=10)),
                ('options', models.JSONField(blank=True, help_text='List of strings for MCQ', null=True)),
                ('correct_answer', models.TextField()),
                ('marks', models.IntegerField(default=3)),
                ('penalty', models.IntegerField(default=1, help_text='Negative marks for wrong answer')),
                ('explanation', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.examquestiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('score_earned', models.FloatField(default=0.0)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='exams.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. VARC, DILR, QA', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=40)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='examquestiongroup',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='exams.examsection'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.examsection'),
        ),
    ]
