# Generated by Django 6.0.3 on 2026-03-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_generator', '0002_quizsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='AI explanation for the correct answer', null=True),
        ),
    ]
