# Generated by Django 6.0.3 on 2026-03-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_generator', '0003_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='gap_analysis',
            field=models.TextField(blank=True, help_text='AI Gap Analysis for Pro users', null=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='study_focus',
            field=models.JSONField(blank=True, help_text='AI-suggested study focus areas', null=True),
        ),
    ]
