# Generated by Django 6.0.3 on 2026-03-17 22:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz_generator', '0004_quizsession_gap_analysis_quizsession_study_focus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('interval', models.IntegerField(default=0, help_text='Days until next review')),
                ('easiness', models.FloatField(default=2.5, help_text='SM-2 Ease Factor')),
                ('repetitions', models.IntegerField(default=0, help_text='Consecutive correct reviews')),
                ('next_review', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_generator.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review'],
            },
        ),
    ]
